### ISSUE TITLE
upload and download all files directory

### ISSUE THREAD

**Issue by socrat3** [Meliox/FTPauto#28]
Hi,

how can i upload and download all files of a directory?

**Comment by Meliox** [comment]
Hello,

Just pass the directory itself, e.g. bash ftpauto.sh --user=someone --path=/some/directory/ and set send_option=default in the users config file.

It's not really made for upload and download at the same time for one user, so you would have to change transferetype=upftp or transferetype=downftp in the users config file depending on your task.

**Comment by socrat3** [comment]
Thx for reply...

i have this error... why? nothing error on single file trasfert

 $: bash ftpauto.sh --user=soc --path=/home/soc/tmp/release.0day/

FTPauto script - 0.5.3


INFO: Information level: 0
INFO: User: soc
INFO: Option(s): download start
INFO: Process id: 28687
INFO: Transfer-option: upftp
INFO: Process start-time: 10/12/17-dom-15:57:52
INFO: Preparing transfer: /home/soc/tmp/release.0day/
INFO: Lunched from: CONSOLE
INFO: Queueid: 1
INFO: Simultaneous transfers: 1
INFO: Size to transfere: 3544.56MB
find: espressione non valida: parentesi vuote non permesse.
INFO: Updated size to transfere(regex used): 0MB
INFO: Sendoption: default
INFO: Transfer started: 10/12/17-dom-15:57:52


INFO: Transfer ended: 10/12/17-dom-15:57:54
(standard_in) 1: syntax error
INFO: Cleanup done
INFO: Transfere finished
                       Name: release.0day
                       Size: 0 MB
                      Speed:  MB/s
              Transfer time: 00h:00m:02s
                 Start time: 10/12/17-dom-15:57:52
                   End time: 10/12/17-dom-15:57:54
                 Total time: 00h:00m:02s
----------------------- Empty queue -----------------------
INFO: Queue is empty. Program will end

Exiting successfully...

**Comment by Meliox** [comment]
Could you send me the debug log (--verbose). Remember to remove any confidential information (ip /password etc).

**Comment by socrat3** [comment]
+ echo 'INFO: Information level: 1'
+ updateChecker
++ date +%s
++ echo 1512905902 + '14*24*60*60'
++ bc
+ [[ 1512919011 -gt 1514115502 ]]
+ [[ -n '' ]]
+ load_user
+ [[ -z soc ]]
+ [[ -n soc ]]
+ [[ -f /home/soc/FTPauto/users/soc/config ]]
+ username=soc
+ config_name=/home/soc/FTPauto/users/soc/default
+ loadDependency DConfig
+ local LoadPath=
+ case "$1" in
+ LoadPath=/home/soc/FTPauto/users/soc/config
+ source /home/soc/FTPauto/users/soc/config
++ config_version=6
++ transferetype=upftp
++ ftpincomplete=
++ ftpcomplete=/www.ftp.com/prova/
++ ftpuser1=user
++ ftppass1=blabla
++ ftphost1=ftp.x.comom
++ ftpport1=21
++ ftpssl1=true
++ ftpcustom1='set ssl:verify-certificate no'
++ ftpuser2=123
++ ftppass2=123
++ ftphost2=ftp.pino.it
++ ftpport2=21
++ ftpssl2=false
++ ftpcustom2=
++ logrotate=false
++ lognumber=50
++ send_option=default
++ splitsize=1000
++ create_sfv=false
++ parallel=1
++ continue_queue=true
++ retries=1
++ retry_download=10
++ retry_download_max=1
++ force=true
++ confirm_transfer=false
++ confirm_online=false
++ exclude_array=
++ ftpsizemanagement=false
++ totalmb=14950
++ critical=100
++ sleeptime=2
++ exec_post=
++ allow_background=false
++ exec_pre=
++ sort=false
++ push_token=
++ push_user=
+ echo 'INFO: User: soc'
+ [[ 6 -ne 6 ]]
+ loadDependency DSetup
+ local LoadPath=
+ case "$1" in
+ LoadPath=/home/soc/FTPauto/dependencies/setup.sh
+ source /home/soc/FTPauto/dependencies/setup.sh
+ setup
+ PATH=/home/soc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ which lftp
+ lftp=/usr/local/bin/lftp
++ which rar2fs
+ rar2fs=
+ queue_file=/home/soc/FTPauto/run/soc.queue
+ lockfile=/home/soc/FTPauto/run/soc.lck
+ logfile=/home/soc/FTPauto/users/soc/log
+ oldlogfile=/home/soc/FTPauto/users/soc/log.old
+ ftptransfere_file=/home/soc/FTPauto/run/soc.ftptransfere
+ ftptransfere_processbar=/home/soc/FTPauto/run/soc.ftpprocessbar
+ ftplogin_file1=/home/soc/FTPauto/run/soc.ftplogin1
+ ftplogin_file2=/home/soc/FTPauto/run/soc.ftplogin2
+ ftpfreespace_file=/home/soc/FTPauto/run/soc.ftpfreespace
+ ftpalive_file=/home/soc/FTPauto/run/soc.ftpalive
+ ftpcheck_testfile=/home/soc/FTPauto/run/soc.testfile
+ ftpcheck_file=/home/soc/FTPauto/run/soc.ftpcheck
+ proccess_bar_file=/home/soc/FTPauto/run/soc.transfered.info
+ ftp_size_file=/home/soc/FTPauto/run/soc.ftpsize.info
+ log_control=/home/soc/FTPauto/run/soc.controllog
+ ftpmaindebugfile=/home/soc/FTPauto/run/soc.ftpmain.debug
+ lftpdebug=/home/soc/FTPauto/run/soc.lftpdebug
+ lftptransfersize=/home/soc/FTPauto/run/soc.ftptransfersize
+ transfersize=/home/soc/FTPauto/run/soc.transfersize
+ transfersize2=/home/soc/FTPauto/run/soc.transfersize2
+ lftptransfersize2=/home/soc/FTPauto/run/soc.lftptransfersize2
+ ftplist_file=/home/soc/FTPauto/run/soc.lftplist
+ ftp_content=/home/soc/FTPauto/run/soc.ftpcontent
+ '[' '!' -e /home/soc/FTPauto/users/soc/log ']'
+ echo 'INFO: Option(s): download' start
+ main
+ safelock=true
+ case "${option[0]}" in
+ safelock=false
+ [[ -z '' ]]
+ source=CONSOLE
+ [[ start == \s\t\a\r\t ]]
+ start_ftpmain
+ loadDependency DFtpMain
+ local LoadPath=
+ case "$1" in
+ LoadPath=/home/soc/FTPauto/dependencies/ftp_main.sh
+ source /home/soc/FTPauto/dependencies/ftp_main.sh
+ [[ 1 -eq 1 ]]
+ start_main --user=soc --path=/home/soc/Scrivania/film/
+ :
+ case "$1" in
+ user=soc
+ shift
+ :
+ case "$1" in
+ filepath=/home/soc/Scrivania/film/
+ shift
+ :
+ case "$1" in
+ break
+ [[ -z /home/soc/Scrivania/film/ ]]
++ find /home/soc/Scrivania/film/ -type d
+ [[ -z /home/soc/Scrivania/film/ ]]
++ find /home/soc/Scrivania/film/ -type f -print
++ head -n 1
+ [[ -z /home/soc/Scrivania/film/Il.Gattopardo.BdRip1080HEVC.mkv ]]
+ [[ '' == true ]]
+ [[ '' == \t\r\u\e ]]
+ lockfile
+ [[ -f /home/soc/FTPauto/run/soc.lck ]]
+ echo
+ echo
+ echo
+ echo
+ echo
+ sed '1c 28291' -i /home/soc/FTPauto/run/soc.lck
+ echo 'INFO: Process id: 28291'
+ echo 'INFO: Transfer-option: upftp'
+ loadDependency DSetup
+ local LoadPath=
+ case "$1" in
+ LoadPath=/home/soc/FTPauto/dependencies/setup.sh
+ source /home/soc/FTPauto/dependencies/setup.sh
+ loadConfig
+ loadDependency DConfig
+ local LoadPath=
+ case "$1" in
+ LoadPath=/home/soc/FTPauto/users/soc/config
+ source /home/soc/FTPauto/users/soc/config
++ config_version=6
++ transferetype=upftp
++ ftpincomplete=
++ ftpcomplete=/www.salvatorecrapanzano.com/prova/
++ ftpuser1=user
++ ftppass1=blabla
++ ftphost1=ftp.x.comom
++ ftpport1=21
++ ftpssl1=true
++ ftpcustom1='set ssl:verify-certificate no'
++ ftpuser2=123
++ ftppass2=123
++ ftphost2=ftp.pino.it
++ ftpport2=21
++ ftpssl2=false
++ ftpcustom2=
++ logrotate=false
++ lognumber=50
++ send_option=default
++ splitsize=1000
++ create_sfv=false
++ parallel=1
++ continue_queue=true
++ retries=1
++ retry_download=10
++ retry_download_max=1
++ force=true
++ confirm_transfer=false
++ confirm_online=false
++ exclude_array=
++ ftpsizemanagement=false
++ totalmb=14950
++ critical=100
++ sleeptime=2
++ exec_post=
++ allow_background=false
++ exec_pre=
++ sort=false
++ push_token=
++ push_user=
+ setup
+ PATH=/home/soc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ which lftp
+ lftp=/usr/local/bin/lftp
++ which rar2fs
+ rar2fs=
+ queue_file=/home/soc/FTPauto/run/soc.queue
+ lockfile=/home/soc/FTPauto/run/soc.lck
+ logfile=/home/soc/FTPauto/users/soc/log
+ oldlogfile=/home/soc/FTPauto/users/soc/log.old
+ ftptransfere_file=/home/soc/FTPauto/run/soc.ftptransfere
+ ftptransfere_processbar=/home/soc/FTPauto/run/soc.ftpprocessbar
+ ftplogin_file1=/home/soc/FTPauto/run/soc.ftplogin1
+ ftplogin_file2=/home/soc/FTPauto/run/soc.ftplogin2
+ ftpfreespace_file=/home/soc/FTPauto/run/soc.ftpfreespace
+ ftpalive_file=/home/soc/FTPauto/run/soc.ftpalive
+ ftpcheck_testfile=/home/soc/FTPauto/run/soc.testfile
+ ftpcheck_file=/home/soc/FTPauto/run/soc.ftpcheck
+ proccess_bar_file=/home/soc/FTPauto/run/soc.transfered.info
+ ftp_size_file=/home/soc/FTPauto/run/soc.ftpsize.info
+ log_control=/home/soc/FTPauto/run/soc.controllog
+ ftpmaindebugfile=/home/soc/FTPauto/run/soc.ftpmain.debug
+ lftpdebug=/home/soc/FTPauto/run/soc.lftpdebug
+ lftptransfersize=/home/soc/FTPauto/run/soc.ftptransfersize
+ transfersize=/home/soc/FTPauto/run/soc.transfersize
+ transfersize2=/home/soc/FTPauto/run/soc.transfersize2
+ lftptransfersize2=/home/soc/FTPauto/run/soc.lftptransfersize2
+ ftplist_file=/home/soc/FTPauto/run/soc.lftplist
+ ftp_content=/home/soc/FTPauto/run/soc.ftpcontent
++ echo /home/soc/Scrivania/film/
++ sed 's/\\./ /g'
+ filepath=/home/soc/Scrivania/film/
+ main /home/soc/Scrivania/film/
+ filepath=/home/soc/Scrivania/film/
+ transfer_path=/home/soc/Scrivania/film/
++ basename /home/soc/Scrivania/film/
+ orig_name=film
+ [[ -f /home/soc/Scrivania/film/ ]]
+ [[ -d /home/soc/Scrivania/film/ ]]
+ tempdir=/home/soc/FTPauto/run/soc-temp/film-temp/
++ date +%s
+ ScriptStartTime=1512919011
++ date --date=@1512919011 +%d/%m/%y-%a-%H:%M:%S
+ echo 'INFO: Process start-time: 10/12/17-dom-16:16:51'
+ echo 'INFO: Preparing transfer: /home/soc/Scrivania/film/'
+ echo 'INFO: Lunched from: CONSOLE'
+ queue add
+ local option i old_id
+ option=
+ case "$1" in
+ [[ '' == true ]]
+ id_old=
+ [[ -e /home/soc/FTPauto/run/soc.queue ]]
+ id=1
+ get_size /home/soc/Scrivania/film/
+ [[ -e /home/soc/FTPauto/run/soc.queue ]]
+ [[ '' == failed ]]
+ [[ '' == end ]]
+ echo 'INFO: Queueid: 1'
++ date +%d/%m/%y-%a-%H:%M:%S
+ echo '1|CONSOLE|/home/soc/Scrivania/film/||0MB|false|10/12/17-dom-16:16:51'
+ echo 'INFO: Simultaneous transfers: 1'
+ get_size /home/soc/Scrivania/film/
+ local dir n count i exp path t_size directorysize
+ dir=/home/soc/Scrivania/film/
+ [[ upftp == downftp ]]
+ [[ upftp == fxp ]]
+ [[ upftp == upftp ]]
++ du -bsL /home/soc/Scrivania/film/
++ awk '{print $1}'
+ directorysize=14100856889
++ bc
++ echo 'scale=2; 14100856889 / (1024*1024)'
+ size=13447.62
+ echo 'INFO: Size to transfere: 13447.62MB'
+ [[ -n 1 ]]
+ exclude_expression=()
+ n=1
+ for i in "${exclude_array[@]}"
+ exclude_expression+=("-iname *$i*")
+ [[ 1 -lt 1 ]]
+ let n++
+ exclude_expression='-iname **'
++ find -L /home/soc/Scrivania/film/ '!' '(' -iname dependencies ftpauto.sh install.sh LICENCE log.txt plugins README.md run users ')' -type f -printf '%s\n'
++ awk -F : '{sum+=$NF} END { printf ("%0.0f\n", sum)}'
find: i percorsi devono precedere le espressioni: ftpauto.sh
Try 'find --help' for more information.
+ sizeBytes=0
++ echo 'scale=2; 0 / (1024*1024)'
++ bc
+ size=0
+ echo 'INFO: Updated size to transfere(regex used): 0MB'
+ [[ -n '' ]]
+ loadDependency DFtpLogin
+ local LoadPath=
+ case "$1" in
+ LoadPath=/home/soc/FTPauto/dependencies/ftp_login.sh
+ source /home/soc/FTPauto/dependencies/ftp_login.sh
+ ftp_login 1
+ local number OIFS IFS ftpcustom ftpssl ftpuser ftppass ftphost ftppass ftploginfile
+ number=1
+ ftpcustom=ftpcustom1
+ ftpssl=ftpssl1
+ ftpuser=ftpuser1
+ ftppass=ftppass1
+ ftphost=ftphost1
+ ftpport=ftpport1
+ ftploginfile=ftplogin_file1
+ echo 'set net:timeout 10'
+ echo 'set net:max-retries 3'
+ echo 'set net:reconnect-interval-base 10'
+ echo 'set net:reconnect-interval-multiplier 1'
+ echo 'set net:reconnect-interval-max 60'
+ (( verbose ))
+ echo 'debug 8 -t -o /home/soc/FTPauto/run/soc.lftpdebug'
+ [[ true == true ]]
+ echo 'set ftp:ssl-force true'
+ echo 'set ssl:verify-certificate false'
+ [[ -n set ssl:verify-certificate no ]]
+ OIFS=
+ IFS=';'
+ for i in "${!ftpcustom[@]}"
+ echo 0
+ IFS=
+ [[ upftp =~ upftp ]]
+ echo 'open -u user,blabla ftp.x.comom -p 21'
+ [[ false == \t\r\u\e ]]
+ [[ false == \t\r\u\e ]]
+ echo 'INFO: Sendoption: default'
+ [[ default == \s\p\l\i\t ]]
+ [[ default == \v\i\d\e\o ]]
+ [[ false == \t\r\u\e ]]
+ [[ -n '' ]]
+ delay
+ local current_epoch target_epoch sleep_seconds timediff
+ [[ -n '' ]]
+ [[ -n '' ]]
+ ftp_transfere
+ local lftp_exclude quittime waittime
+ [[ -n 1 ]]
+ [[ '' = directory ]]
+ [[ -d /home/soc/Scrivania/film/ ]]
+ (( i=0 ))
+ (( i<1 ))
+ [[ 0 -gt 0 ]]
+ lftp_exclude='^.**'
+ (( i++ ))
+ (( i<1 ))
+ lftp_exclude='^.**$'
+ echo 'set mirror:exclude-regex "^.**$"'
+ echo 'set mirror:no-empty-dirs true'
+ [[ upftp == \d\o\w\n\f\t\p ]]
+ [[ upftp == \u\p\f\t\p ]]
+ cat /home/soc/FTPauto/run/soc.ftplogin1
+ echo 'mkdir -p "/www.salvatorecrapanzano.com/prova/"'
+ [[ -n '' ]]
+ echo 'set cmd:fail-exit true'
+ [[ -f /home/soc/Scrivania/film/ ]]
+ [[ -d /home/soc/Scrivania/film/ ]]
+ [[ -n '' ]]
+ [[ -z '' ]]
+ echo 'queue mirror --no-umask -p --parallel=1 -c -RL "/home/soc/Scrivania/film/" "/www.salvatorecrapanzano.com/prova/"'
+ echo wait
+ [[ -n '' ]]
+ echo quit
+ [[ '' != \t\r\u\e ]]
+ ftp_transfer_process start
+ local pid_f_process
+ case "$1" in
++ date +%s
+ TransferStartTime=1512919011
+ pid_f_process=28343
+ sed '3c 28343' -i /home/soc/FTPauto/run/soc.lck
+ ftp_processbar
+ local transfered_size ProgressTimeNew TransferredNew TransferredNewMB TotalTimeDiff TimeDiff percentage speed eta etatime SpeedOld sum SpeedAverage cols percentagebarlength string string2 TransferredOld ProgressTimeOld
+ [[ '' != \t\r\u\e ]]
+ sleep 5
++ date --date=@1512919011 +%d/%m/%y-%a-%H:%M:%S
+ echo -e '\e[00;37mINFO: \e[00;32mTransfer started: 10/12/17-dom-16:16:51\n\e[00m'
+ pid_transfer=28347
+ sed '2c 28347' -i /home/soc/FTPauto/run/soc.lck
+ /usr/local/bin/lftp -f /home/soc/FTPauto/run/soc.ftptransfere
+ wait 28347
+ pid_transfer_status=0
++ date +%s
+ TransferEndTime=1512919011
+ [[ 0 -ne 0 ]]
+ ftp_transfer_process stop-process-bar
+ local pid_f_process
+ case "$1" in
++ sed -n 3p /home/soc/FTPauto/run/soc.lck
+ kill 28343
++ sed -n 3p /home/soc/FTPauto/run/soc.lck
+ wait 28343
++ sed -n 4p /home/soc/FTPauto/run/soc.lck
+ kill
++ sed -n 4p /home/soc/FTPauto/run/soc.lck
+ wait
++ date --date=@1512919011 +%d/%m/%y-%a-%H:%M:%S
+ echo -e '\n\e[00;37mINFO: \e[00;32mTransfer ended: 10/12/17-dom-16:16:51\e[00m'
+ [[ false == \t\r\u\e ]]
+ [[ '' != true ]]
+ logrotate
+ [[ '' != \t\r\u\e ]]
+ transferTime=0
++ printf %02dh:%02dm:%02ds 0 0 0
+ transferTime2=00h:00m:00s
++ sed -n 5p /home/soc/FTPauto/run/soc.lck
+ SpeedAverage=
++ date --date=@1512919011 +%d/%m/%y-%a-%H:%M:%S
+ sed '7i 10/12/17-dom-16:16:51|CONSOLE|film|0MB|00h:00m:00s|MB/s' -i /home/soc/FTPauto/users/soc/log
+ lognumber=57
+ [[ false == \t\r\u\e ]]
+ '[' 57 -ne 0 ']'
+ sed '57,$d' -i /home/soc/FTPauto/users/soc/log
++ awk 'BEGIN{FS="|";OFS=" "}NR==2{print $1}' /home/soc/FTPauto/users/soc/log
++ cut '-d ' -f4
+ totaldl=
+ totaldl=
+ [[ -z '' ]]
+ totaldl=0
++ echo '0 + 0'
++ bc
+ totaldl=0
++ awk 'BEGIN{FS="|";OFS=" "}NR==2{print $1}' /home/soc/FTPauto/users/soc/log
++ cut '-d ' -f6
+ totalrls=
++ echo ' + 1'
++ bc
(standard_in) 1: syntax error
+ totalrls=
++ awk 'BEGIN{FS="|";OFS=" "}NR==2{print $1}' /home/soc/FTPauto/users/soc/log
++ cut '-d ' -f10
+ totaldltime=
++ awk 'BEGIN{split("",a,":"); print a[1]*(60*60*24)+a[2]*(60*60)+a[3]*60+a[4];}'
+ totaldltime_seconds=0
++ echo '0 + 0'
++ bc
+ totaldltime=0
++ printf %02dd:%02dh:%02dm:%02ds 0 0 0 0
+ totaldltime=00d:00h:00m:00s
+ sed '1s#.*#*****  FTPauto 0.5.3#' -i /home/soc/FTPauto/users/soc/log
+ sed '2s#.*#*****  STATS: 0MB in  transfers in 00d:00h:00m:00s#' -i /home/soc/FTPauto/users/soc/log
+ sed '3s#.*#*****  FTP INFO: N/A#' -i /home/soc/FTPauto/users/soc/log
++ date
+ sed '4s#.*#*****  LASTDL: dom 10 dic 2017, 16.16.51, CET|film|MB/s#' -i /home/soc/FTPauto/users/soc/log
+ sed '5s#.*#*****  #' -i /home/soc/FTPauto/users/soc/log
+ cleanup session
+ local array
+ case "$1" in
+ [[ '' == \t\r\u\e ]]
+ [[ '' == \t\r\u\e ]]
+ array=("$ftplogin_file1" "$ftplogin_file2" "$ftptransfere_file" "$ftp_size_file" "$ftpfreespace_file" "$lftptransfersize" "$lftptransfersize2" "$transfersize" "$transfersize2" "$proccess_bar_file" "$ftpalive_file" "$ftpcheck_file" "$ftpcheck_testfile" "$ftptransfere_processbar")
+ removeClean /home/soc/FTPauto/run/soc.ftplogin1 /home/soc/FTPauto/run/soc.ftplogin2 /home/soc/FTPauto/run/soc.ftptransfere /home/soc/FTPauto/run/soc.ftpsize.info /home/soc/FTPauto/run/soc.ftpfreespace /home/soc/FTPauto/run/soc.ftptransfersize /home/soc/FTPauto/run/soc.lftptransfersize2 /home/soc/FTPauto/run/soc.transfersize /home/soc/FTPauto/run/soc.transfersize2 /home/soc/FTPauto/run/soc.transfered.info /home/soc/FTPauto/run/soc.ftpalive /home/soc/FTPauto/run/soc.ftpcheck /home/soc/FTPauto/run/soc.testfile /home/soc/FTPauto/run/soc.ftpprocessbar
+ local array
+ array=("$@")
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftplogin1
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftplogin2
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftptransfere
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftpsize.info
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftpfreespace
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftptransfersize
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.lftptransfersize2
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.transfersize
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.transfersize2
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.transfered.info
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftpalive
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftpcheck
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.testfile
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.ftpprocessbar
+ [[ -d /home/soc/FTPauto/run/soc-temp ]]
+ echo -e 'INFO: Cleanup done'
+ [[ -n '' ]]
+ [[ -n '' ]]
++ date +%s
+ ScriptEndTime=1512919011
+ TotalTransferTime=0
+ [[ '' == true ]]
+ echo -e '\e[00;37mINFO: \e[00;32mTransfere finished\e[00m'
+ echo '                       Name: film'
+ echo '                       Size: 0 MB'
+ echo '                      Speed:  MB/s'
+ echo '              Transfer time: 00h:00m:00s'
++ date --date=@1512919011 +%d/%m/%y-%a-%H:%M:%S
+ echo '                 Start time: 10/12/17-dom-16:16:51'
++ date --date=@1512919011 +%d/%m/%y-%a-%H:%M:%S
+ echo '                   End time: 10/12/17-dom-16:16:51'
++ printf %02dh:%02dm:%02ds 0 0 0
+ echo '                 Total time: 00h:00m:00s'
+ [[ '' != true ]]
+ queue remove
+ local option i old_id
+ option=
+ case "$1" in
+ sed '/^1/d' -i /home/soc/FTPauto/run/soc.queue
+ [[ true == true ]]
+ queue next
+ local option i old_id
+ option=
+ case "$1" in
+ [[ -f /home/soc/FTPauto/run/soc.queue ]]
++ cat /home/soc/FTPauto/run/soc.queue
+ [[ -n '' ]]
+ echo '----------------------- Empty queue -----------------------'
+ [[ -f /home/soc/FTPauto/run/soc.queue ]]
+ rm /home/soc/FTPauto/run/soc.queue
+ echo -e 'INFO: Queue is empty. Program will end\n'
+ cleanup end
+ local array
+ case "$1" in
+ removeClean /home/soc/FTPauto/run/soc.lck
+ local array
+ array=("$@")
+ for i in "${array[@]}"
+ rm -f /home/soc/FTPauto/run/soc.lck
+ sed '5s#.*#***************************	#' -i /home/soc/FTPauto/users/soc/log
+ echo -e '\e[00;32mExiting successfully...\e[00m\n'
+ exit 0

**Comment by Meliox** [comment]
Thanks for the log. Helped me a lot!
Found a few bugs. 1) If you had an empty exclude_array, the size could not be calculated, 2) Trailing slash would cause the content in the directory to be transferred and not the whole directory itself. 

Please try version 0.5.4.

**Comment by socrat3** [comment]
thx for your job
