### ISSUE TITLE
Have to create 'run' directory manually after installation and adding a user

### ISSUE THREAD

**Issue by lixiaoquan** [Meliox/FTPauto#33]
It doesn't seems to work before I create `FTPAuto/run` manually. Without this directory, it keeps on printing 
```
/home/xiaoquan.li/FTPauto/dependencies/ftp_main.sh: line 557: /home/xiaoquan.li/FTPauto/run/xiaoquan.li.lck: No such file or directory
```

**Comment by Meliox** [comment]
Did you install using install.sh?

**Comment by lixiaoquan** [comment]
Yes, I executed
```
bash install.sh install
```

**Comment by Meliox** [comment]
Thanks for pointing this out. The installer was quite broken, old packages that cannot be found anymore.
The installer has got quite the overhaul in 647c9f88521904342842f32da9db17dff1f7c951

**Comment by Meliox** [comment]
I will push a small update to correct the installer in the package installed.
